### ISSUE TITLE
Different Exception Type between Sync and Async client

### ISSUE THREAD

**Issue by laucia** [Yelp/swagger-py#134] opened 2015-03-29 11:12 UTC
Swagger-py's HTTPError is an exact copy of request's one
https://github.com/Yelp/swagger-py/blob/master/swaggerpy/exception.py#L9-L21
https://github.com/kennethreitz/requests/blob/master/requests/exceptions.py#L13-L31

but the SynchronousHttpClient throws requests.exceptions.HTTPError, and AsynchronousHttpClient throws swaggerpy.exception.HTTPError which makes error handling closely tied to the client used.

replacing the HTTPError code in swaggerpy/exception.py by a from requests.exceptions import HTTPError could solve this and by backward compatible.

**Comment by dnephin** [comment] 2015-03-29 16:43
Duplicate of #100

**Comment by prat0318** [comment] 2015-04-01 00:08
Closing it. Progress is tracked from now in #100.

**Closed by prat0318** 2015-04-01 00:08 UTC
